name: Felipe G. Bogo
shortname: felipegbogo
url: https://felipegbogo.github.io
title: Ph.D. Candidate - Geometria Diferencial & Conforme
email: felipegbogo@gmail.com
twitter_username: false
github_username: felipegbogo

collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publication/:path/
